Repository TeamBookTez/booktez-server, pull requests merged in 2022-04, with the labels that each got.

#139 [feat] Add a method if a review already exists
  src/controller/book.ts
  src/router/book.ts
  src/service/book.ts
Labels: 🍀 feature, 1️⃣ priority: high

#140 [feat] Implement membership withdrawal logic
  package-lock.json
  package.json
  src/controller/auth.ts
  src/index.ts
  src/interface/IUser.ts
  src/loader/db.ts
  src/models/User.ts
  src/router/auth.ts
  src/scheduler/userScheduler.ts
  src/service/auth.ts
Labels: 🍀 feature, 1️⃣ priority: high

#141 [release] v2.1.0
  README.md
  package-lock.json
  package.json
  src/config/index.ts
  src/controller/auth.ts
  src/controller/book.ts
  src/index.ts
  src/interface/IUser.ts
  src/loader/db.ts
  src/middleware/authMiddleware.ts
  src/middleware/upload.ts
  src/models/Book.ts
  src/models/User.ts
  src/others/slack/slackAPI.ts
  src/router/auth.ts
  src/router/book.ts
  src/scheduler/userScheduler.ts
  src/service/auth.ts
  src/service/book.ts
Labels: 🍀 feature

#142 [fix] Typescript compile error on bookService
  src/service/book.ts
Labels: 🔨 fix, 2️⃣ priority: middle
