Repository TeamBookTez/booktez-server, pull requests merged in 2022-01, with the labels that each got.

#5 fix: foreign key error
  src/models/Book.ts
  src/models/Review.ts
Labels: 🔨 fix, 1️⃣ priority: high

#7 feat: response
  src/library/response.ts
Labels: 🍀 feature, 2️⃣ priority: middle

#9 Feat/s3 access key
  package-lock.json
  package.json
  src/config/index.ts
  src/models/index.ts
Labels: 🍀 feature, 2️⃣ priority: middle

#13 Feat/middleware
  src/middleware/auth.ts
  src/middleware/isLogin.ts
Labels: 🍀 feature, 2️⃣ priority: middle

#15 Feat/login api
  package-lock.json
  src/controller/auth.ts
  src/controller/test.ts
  src/library/constant.ts
  src/router/auth.ts
  src/router/index.ts
  src/service/auth.ts
Labels: 🍀 feature, 🔨 fix, 1️⃣ priority: high

#21 Fix/signup api
  src/controller/auth.ts
  src/router/auth.ts
  src/service/auth.ts
Labels: 🔨 fix, 2️⃣ priority: middle

#19 Fix/login api
  src/controller/auth.ts
  src/service/auth.ts
Labels: 🌈 refactor, 2️⃣ priority: middle

#26 Feat/get book api
  src/controller/book.ts
  src/router/book.ts
  src/router/index.ts
  src/service/book.ts
Labels: 🍀 feature, 1️⃣ priority: high

#31 Fix/login my info api
  src/controller/auth.ts
  src/service/auth.ts
  src/service/user.ts
Labels: 🔨 fix, 🌈 refactor, 2️⃣ priority: middle

#32 Feat/post book api
  src/controller/book.ts
  src/middleware/isLogin.ts
  src/router/book.ts
  src/service/book.ts
Labels: 🍀 feature, 1️⃣ priority: high

#37 Fix/review before
  src/controller/review.ts
  src/service/review.ts
Labels: 🔨 fix, 1️⃣ priority: high

#38 Feat/patch review review id api
  src/controller/review.ts
  src/library/constant.ts
  src/router/review.ts
  src/service/review.ts
Labels: 🍀 feature, 1️⃣ priority: high

#42 feat: get review api
  src/controller/review.ts
  src/library/constant.ts
  src/router/review.ts
  src/service/review.ts
Labels: 🍀 feature, 1️⃣ priority: high

#40 Feat/review now
  src/controller/review.ts
  src/router/review.ts
  src/service/review.ts
Labels: 🍀 feature, 2️⃣ priority: middle

#43 Feat/patch img api
  package-lock.json
  package.json
  src/controller/user.ts
  src/index.ts
  src/middleware/upload.ts
  src/router/user.ts
  src/service/user.ts
Labels: 🍀 feature, 1️⃣ priority: high

#45 Feat/review delete
  .gitignore
  package-lock.json
  src/controller/review.ts
  src/library/constant.ts
  src/router/review.ts
  src/service/review.ts
Labels: 🍀 feature, 2️⃣ priority: middle

#50 Feat/get user email api
  src/controller/auth.ts
  src/router/auth.ts
  src/service/auth.ts
Labels: 🍀 feature, 1️⃣ priority: high

#51 Feat/nickname api
  src/controller/auth.ts
  src/controller/user.ts
  src/router/auth.ts
  src/service/auth.ts
Labels: 🍀 feature, 1️⃣ priority: high

#53 Feat/question list
  src/controller/review.ts
  src/router/review.ts
  src/service/review.ts
Labels: 🍀 feature, 1️⃣ priority: high

#55 Fix/database structure
  src/models/Book.ts
  src/models/Review.ts
  src/models/User.ts
Labels: 🐞 bug, 🔨 fix, 🌈 refactor, 1️⃣ priority: high

#64 Fix/finish state
  src/controller/review.ts
  src/library/constant.ts
  src/service/review.ts
Labels: 🔨 fix, 2️⃣ priority: middle

#65 Fix/email nickname validation api
  src/controller/auth.ts
  src/library/checkValidation.ts
  src/router/auth.ts
  src/service/auth.ts
Labels: 🔨 fix, 2️⃣ priority: middle

#66 Fix/my info bug
  src/controller/user.ts
  src/library/constant.ts
  src/router/user.ts
  src/service/auth.ts
  src/service/review.ts
  src/service/user.ts
Labels: 🐞 bug, 🔨 fix, 1️⃣ priority: high

#69 Fix/middleware
  src/controller/book.ts
  src/controller/review.ts
  src/controller/user.ts
  src/middleware/auth.ts
  src/middleware/authMiddleware.ts
  src/middleware/isLogin.ts
  src/router/book.ts
  src/router/review.ts
  src/router/user.ts
  src/service/book.ts
Labels: 🌈 refactor, 2️⃣ priority: middle

#76 fix: patch-package
  patches/@types+express-serve-static-core+4.17.28.patch
Labels: 🔨 fix, 🌈 refactor, 1️⃣ priority: high, 2️⃣ priority: middle

#77 refactor: controller and service structure change
  src/controller/auth.ts
  src/controller/book.ts
  src/controller/review.ts
  src/controller/test.ts
  src/controller/user.ts
  src/library/constant.ts
  src/middleware/authMiddleware.ts
  src/router/auth.ts
  src/router/book.ts
  src/router/index.ts
  src/router/review.ts
  src/router/test.ts
  src/service/auth.ts
  src/service/book.ts
  src/service/review.ts
  src/service/test.ts
  src/service/user.ts
Labels: 🌈 refactor, 2️⃣ priority: middle

#82 Fix/flow
  src/controller/review.ts
  src/router/review.ts
  src/service/review.ts
Labels: 🔨 fix, 1️⃣ priority: high

#86 Test/add test code
  package-lock.json
  package.json
  src/library/checkValidation.ts
  src/service/review.ts
  src/test/library/checkValidation.spec.ts
  src/test/service/auth.spec.ts
  src/test/service/book.spec.ts
  src/test/service/review.spec.ts
  src/test/service/user.spec.ts
Labels: 🍀 feature, 1️⃣ priority: high
