Repository TeamBookTez/booktez-server, pull requests merged in 2022-03, with the labels that each got.

#119 [refactor] Change database to MongoDB
  package-lock.json
  package.json
  src/.sequelizerc.ts
  src/config/config.ts
  src/config/index.ts
  src/controller/auth.ts
  src/controller/book.ts
  src/controller/review.ts
  src/index.ts
  src/interface/IBook.ts
  src/interface/IReview.ts
  src/interface/IUser.ts
  src/library/convertSnakeToCamel.ts
  src/loader/db.ts
  src/middleware/authMiddleware.ts
  src/middleware/upload.ts
  src/models/Book.ts
  src/models/Review.ts
  src/models/User.ts
  src/models/index.ts
  src/service/auth.ts
  src/service/book.ts
  src/service/review.ts
  src/service/user.ts
Labels: 🌈 refactor, 1️⃣ priority: high

#124 [feat] Add mongo id form valid checker
  src/controller/review.ts
  src/service/review.ts
Labels: 🍀 feature, 3️⃣ priority: low

#125 [fix] Modify Book find query
  src/service/review.ts
Labels: 🔨 fix, 1️⃣ priority: high

#135 [refactor] Add configuration manager
  src/config/index.ts
  src/index.ts
  src/middleware/authMiddleware.ts
  src/middleware/upload.ts
  src/models/Book.ts
  src/models/User.ts
  src/others/slack/slackAPI.ts
  src/service/auth.ts
Labels: 🌈 refactor, 3️⃣ priority: low
