Repository TeamBookTez/booktez-server, pull requests merged in 2022-02, with the labels that each got.

#94 Refactor/change variable name
  src/controller/book.ts
  src/controller/review.ts
  src/service/book.ts
  src/service/review.ts
Labels: 🌈 refactor, 2️⃣ priority: middle

#95 Refactor/modify uri
  src/controller/review.ts
  src/router/review.ts
  src/service/review.ts
  src/test/service/review.spec.ts
Labels: 🌈 refactor, 2️⃣ priority: middle

#97 Feat/get book detail api
  src/controller/book.ts
  src/router/book.ts
  src/service/book.ts
Labels: 🍀 feature, 🌈 refactor, 1️⃣ priority: high

#103 fix: review-api questionList response structure
  src/service/review.ts
Labels: 🔨 fix, 1️⃣ priority: high

#104 fix: remove slack webhook message from jwt middlewares
  src/middleware/authMiddleware.ts
Labels: 🔨 fix, 3️⃣ priority: low

#108 [feat] Create Issue & PR template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/fix.md
  .github/ISSUE_TEMPLATE/refactor.md
  .github/PULL_REQUEST_TEMPLATE
  .gitignore
Labels: 🍀 feature, 3️⃣ priority: low

#105 Refactor/switch database from postgreSQL to MongoDB
  package-lock.json
  package.json
  src/config/config.ts
  src/config/index.ts
  src/index.ts
  src/interface/IBook.ts
  src/interface/IReview.ts
  src/interface/IUser.ts
  src/loader/db.ts
  src/models/Book.ts
  src/models/Review.ts
  src/models/User.ts
  src/models/index.ts
Labels: 🌈 refactor, 1️⃣ priority: high

#110 [refactor] login response structure
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/fix.md
  .github/ISSUE_TEMPLATE/refactor.md
  src/service/auth.ts
Labels: 🌈 refactor, 2️⃣ priority: middle

#116 [refactor] modify api mongo db
  package-lock.json
  src/service/auth.ts
  src/service/review.ts
  src/service/user.ts
Labels: 🌈 refactor, 1️⃣ priority: high

#117 Refactor/book review api
  src/controller/review.ts
  src/index.ts
  src/router/index.ts
  src/service/book.ts
  src/service/review.ts
Labels: 🌈 refactor, 1️⃣ priority: high
